version: 2

sphinx:
   configuration: docs/conf.py

build:
   os: ubuntu-24.04
   tools:
      python: "3.13"

   jobs:
      pre_create_environment:
         - asdf plugin add uv
         - asdf install uv latest
         - asdf global uv latest
      create_environment:
         - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
      install:
        # Building the project in readthedocs is a pain, we
        # fake it by installing the latest version TODO better solution
         - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --no-install-project
         - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv pip install planegcs
